name: DP-Menu
version: 2.0.0
main: com.darksoldier1404.dpm.Menu
api-version: 1.14
authors: [ DEAD_POOLIO_, BlueEarthCat ]
depend:
  - DPP-Core
softdepend:
  - Essentials
  - PlaceholderAPI
commands:
  dpm:
    aliases: [ dpmenu ]